name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and Push Docker image
      run: |
        echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u "intime333" --password-stdin
        docker build -t cool_docker .
        docker tag cool_docker intime333/nice_docker:latest
        docker push intime333/nice_docker:latest

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin

    - name: Get GKE credentials
      run: |
        gcloud --version
        gcloud container clusters get-credentials cst407-cloudcomputing-tanel --region us-central1

    #- name: Create kubeconfig
     # run: |
      #  mkdir -p ${HOME}/.kube
       # echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config

    - name: Verify kubectl configuration
      run: |
        kubectl version
        kubectl config view

    - name: Restart Kubernetes Deployment
      run: kubectl rollout restart deployment cst407-deployment
